IPDatabase.py: don't checkout specified version if current version newer
pulp-platform/IPApproX pull request #7
Opened 2019-07-17 16:54 UTC by vogelpi

This commit modifies `update_ips()` to check the timestamp of the
current IP version and the version specified in the manifest. If
the current IP version is newer than the specified version, the
checkout is not performed and a warning is printed.

This is useful if experimenting with newer IP versions in hierarchical
flows such as PULPIssimo. Without this commit, the user has to first
update and commit & push `ips_list.yml` of the higher-level IP, and
then do the same with the top-level `ips_list.yml` which is a lot of
overhead. Otherwise, the tool refuses to work with a newer IP version
and always checks out the older version specified in the `ips_list.yml`
of the higher-level IP.

2019-08-09 13:39 UTC, bluewww commented
I agree with this change in principle. Still I think there should be a command line parameter called `--force` or something to get the old behaviour.

2019-08-13 10:22 UTC, vogelpi commented
Hi @bluewww , that's a good idea. I will add a new parameter for this.

2019-08-16 14:05 UTC, vogelpi commented
Hi @bluewww , I made the feature controllable by a new parameter `force_downgrade`.

2019-10-08 15:24 UTC, bluewww requested changes

2019-10-08 15:24 UTC, bluewww commented on ipstools/IPDatabase.py
> +    def update_ips(self, origin='origin', force_downgrade=False):
Default should be `force_downgrade=True` in discussion with @meggiman

2019-10-08 15:27 UTC, FrancescoConti commented on ipstools/IPDatabase.py
> +    def update_ips(self, origin='origin', force_downgrade=False):
Yes I entirely agree, in this way we keep the original behavior as default...

2020-02-03 14:47 UTC, vogelpi commented on ipstools/IPDatabase.py
> +    def update_ips(self, origin='origin', force_downgrade=False):
I know, it's a long time ago. I changed the parameter to True to get the same default behavior as before.

2020-02-04 18:01 UTC, bluewww approved these changes
Tested in on the PULP repository. LGTM.

2020-02-05 14:40 UTC, merged